/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    workspaces: Workspace;
    pages: Page;
    databases: Database;
    'database-rows': DatabaseRow;
    projects: Project;
    'task-statuses': TaskStatus;
    tasks: Task;
    'task-links': TaskLink;
    followers: Follower;
    comments: Comment;
    activity: Activity;
    notifications: Notification;
    artifacts: Artifact;
    plugins: Plugin;
    'runtime-profiles': RuntimeProfile;
    runtimes: Runtime;
    agents: Agent;
    approvals: Approval;
    'saved-views': SavedView;
    'push-subscriptions': PushSubscription;
    'notification-preferences': NotificationPreference;
    'project-resources': ProjectResource;
    'workspace-members': WorkspaceMember;
    invitations: Invitation;
    'access-grants': AccessGrant;
    connectors: Connector;
    connections: Connection;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    workspaces: WorkspacesSelect<false> | WorkspacesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    databases: DatabasesSelect<false> | DatabasesSelect<true>;
    'database-rows': DatabaseRowsSelect<false> | DatabaseRowsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'task-statuses': TaskStatusesSelect<false> | TaskStatusesSelect<true>;
    tasks: TasksSelect<false> | TasksSelect<true>;
    'task-links': TaskLinksSelect<false> | TaskLinksSelect<true>;
    followers: FollowersSelect<false> | FollowersSelect<true>;
    comments: CommentsSelect<false> | CommentsSelect<true>;
    activity: ActivitySelect<false> | ActivitySelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    artifacts: ArtifactsSelect<false> | ArtifactsSelect<true>;
    plugins: PluginsSelect<false> | PluginsSelect<true>;
    'runtime-profiles': RuntimeProfilesSelect<false> | RuntimeProfilesSelect<true>;
    runtimes: RuntimesSelect<false> | RuntimesSelect<true>;
    agents: AgentsSelect<false> | AgentsSelect<true>;
    approvals: ApprovalsSelect<false> | ApprovalsSelect<true>;
    'saved-views': SavedViewsSelect<false> | SavedViewsSelect<true>;
    'push-subscriptions': PushSubscriptionsSelect<false> | PushSubscriptionsSelect<true>;
    'notification-preferences': NotificationPreferencesSelect<false> | NotificationPreferencesSelect<true>;
    'project-resources': ProjectResourcesSelect<false> | ProjectResourcesSelect<true>;
    'workspace-members': WorkspaceMembersSelect<false> | WorkspaceMembersSelect<true>;
    invitations: InvitationsSelect<false> | InvitationsSelect<true>;
    'access-grants': AccessGrantsSelect<false> | AccessGrantsSelect<true>;
    connectors: ConnectorsSelect<false> | ConnectorsSelect<true>;
    connections: ConnectionsSelect<false> | ConnectionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'hermes-config': HermesConfig;
  };
  globalsSelect: {
    'hermes-config': HermesConfigSelect<false> | HermesConfigSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * URL to the user avatar image
   */
  avatar?: string | null;
  role: 'admin' | 'member';
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workspaces".
 */
export interface Workspace {
  id: number;
  /**
   * Never displayed. Presence only.
   */
  composioApiKey?: string | null;
  name: string;
  slug: string;
  /**
   * Emoji or icon identifier
   */
  icon?: string | null;
  owner: number | User;
  members?: (number | User)[] | null;
  /**
   * Short, human-readable task-id prefix for this workspace (e.g. "ENG") — combined with taskCounter for IDs like ENG-142. Not yet surfaced in any UI.
   */
  taskPrefix?: string | null;
  /**
   * Last-issued sequence number for this workspace's human-readable task IDs — increment and read atomically when actually wiring ENG-142-style IDs.
   */
  taskCounter?: number | null;
  /**
   * Monthly spend cap in cents for this workspace, or empty for uncapped. Not yet enforced by the dispatcher (see AGENTS.md B-6 entry).
   */
  spendCapCents?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Emoji used as the page icon
   */
  icon?: string | null;
  /**
   * URL of the page cover image
   */
  coverImage?: string | null;
  workspace: number | Workspace;
  /**
   * Which DataSource backend this page mirrors a row from, if any — set together with linkedSourceId/linkedRecordId. Empty for a regular, unlinked page.
   */
  linkedSourceType?: ('userDatabase' | 'payload' | 'team') | null;
  /**
   * The linked backend's own identifier: a `databases` doc id for 'userDatabase', a collection slug for 'payload', or a `teams` id for 'team'.
   */
  linkedSourceId?: string | null;
  /**
   * The specific row/document id within linkedSourceId.
   */
  linkedRecordId?: string | null;
  /**
   * Parent page for infinite nesting; empty for a top-level page
   */
  parentPage?: (number | null) | Page;
  /**
   * Project this page belongs to, if any — scopes it into the project detail page's Pages tab.
   */
  project?: (number | null) | Project;
  /**
   * Manual drag-and-drop ordering within the sidebar
   */
  position?: number | null;
  /**
   * BlockSuite / Yjs document snapshot
   */
  docState?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Auto-extracted plain text used for search and agent context
   */
  plainTextContent?: string | null;
  isFavorite?: boolean | null;
  isArchived?: boolean | null;
  isFullWidth?: boolean | null;
  isLocked?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  name: string;
  workspace: number | Workspace;
  /**
   * Emoji or icon identifier
   */
  icon?: string | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "databases".
 */
export interface Database {
  id: number;
  name: string;
  workspace: number | Workspace;
  /**
   * Array of GenericField-shaped property definitions ({id, name, type, options?, isPrimary?}) — the user-editable schema for this database.
   */
  fields?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "database-rows".
 */
export interface DatabaseRow {
  id: number;
  database: number | Database;
  /**
   * fieldId -> cell value map
   */
  cells?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Fractional manual ordering within the database (cheap now, per the roadmap's own 2.1 guidance on `position float`)
   */
  position?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "task-statuses".
 */
export interface TaskStatus {
  id: number;
  workspace: number | Workspace;
  /**
   * Free-text, per-workspace label (e.g. "Backlog", "In Progress", "Blocked on design"). Never read by anything except the UI — see category.
   */
  name: string;
  /**
   * The fixed vocabulary every consumer (board grouping, automation, the broker) reads instead of name.
   */
  category: 'backlog' | 'todo' | 'inProgress' | 'inReview' | 'done' | 'blocked' | 'cancelled';
  /**
   * Optional display color token for the status chip/column header.
   */
  color?: string | null;
  /**
   * Manual ordering of statuses within a workspace (e.g. left-to-right board column order).
   */
  position?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tasks".
 */
export interface Task {
  id: number;
  title: string;
  workspace: number | Workspace;
  project?: (number | null) | Project;
  status: number | TaskStatus;
  assignee?: (number | null) | User;
  agent?: (number | null) | Agent;
  /**
   * The task's document (ROADMAP 6.1 — "streams blocks into the task's document"). Null until something needs to write into it: lazily created/linked by lib/task-pages.ts's ensureTaskPage, not on task creation, so a task an agent never touches never gets a page nobody opens.
   */
  page?: (number | null) | Page;
  /**
   * Who created this task — passed explicitly by the caller (see class comment above for why this can't be read off req.user).
   */
  createdBy: number | User;
  /**
   * Fractional manual ordering (e.g. within a board column) — see collection comment.
   */
  position?: number | null;
  /**
   * Optimistic-concurrency counter, incremented automatically on every update. Clients should send back the revision they read; rejecting/merging a stale write is not yet wired up.
   */
  revision?: number | null;
  /**
   * Denormalized "most recently active" timestamp, updated automatically on every change, so sorting never has to join activity.
   */
  lastActivityAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agents".
 */
export interface Agent {
  id: number;
  name: string;
  workspace: number | Workspace;
  runtimeProfile: number | RuntimeProfile;
  model?: string | null;
  hermesProfile?: string | null;
  runtimeConfig?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  thinkingLevel?: ('low' | 'medium' | 'high') | null;
  instructions?: string | null;
  customEnv?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  customArgs?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  mcpConfig?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  skills?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  maxConcurrentRuns?: number | null;
  permissionMode: 'ask' | 'auto' | 'deny';
  enabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "runtime-profiles".
 */
export interface RuntimeProfile {
  id: number;
  name: string;
  workspace: number | Workspace;
  protocolFamily: 'acp' | 'mcp';
  commandName: string;
  fixedArgs?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  enabled?: boolean | null;
  homeStrategy?: ('hermes' | 'none') | null;
  handshake?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  defaultSessionConfig?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  lastProbeCode?: string | null;
  lastProbeDetail?: string | null;
  lastProbedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "task-links".
 */
export interface TaskLink {
  id: number;
  fromTask: number | Task;
  toTask: number | Task;
  linkType: 'blocks' | 'relatesTo' | 'parentOf';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "followers".
 */
export interface Follower {
  id: number;
  user: number | User;
  entityType: 'task' | 'project' | 'page';
  entityId: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments".
 */
export interface Comment {
  id: number;
  task: number | Task;
  author: number | User;
  body: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity".
 */
export interface Activity {
  id: number;
  entityType: 'task' | 'project' | 'page' | 'run';
  entityId: string;
  /**
   * Nullable: system/automation-generated activity has no human actor.
   */
  actor?: (number | null) | User;
  /**
   * Verb describing what happened (e.g. "created", "commented", "status_changed").
   */
  action: string;
  /**
   * Action-specific details (e.g. { from: "todo", to: "done" } for a status_changed action).
   */
  payload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  user: number | User;
  activity?: (number | null) | Activity;
  /**
   * Fallback display text for a notification with no backing activity row.
   */
  message?: string | null;
  isRead?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artifacts".
 */
export interface Artifact {
  id: number;
  /**
   * The tenancy boundary. Every artifact belongs to exactly one workspace.
   */
  workspace: number | Workspace;
  name: string;
  /**
   * 'page' points at a real BlockSuite document; 'html' carries its body in htmlContent.
   */
  kind: 'page' | 'html';
  /**
   * The document itself, when kind is "page". The artifact is only a pointer — docState, search text and history stay in Pages.
   */
  page?: (number | null) | Page;
  /**
   * BlockSuite block id inside `page` that the authoring run owns and appends under. Set by lib/artifacts.ts; never edited by hand.
   */
  pageSubtreeBlockId?: string | null;
  /**
   * The document body, when kind is "html". Rendered sandboxed and never same-origin (R8.7).
   */
  htmlContent?: string | null;
  /**
   * The field the R8.3 placement rule turns on. Empty means loose — the artifact sits in the Artifacts inbox. Setting it MOVES the artifact (and its page) into that project and out of the inbox.
   */
  project?: (number | null) | Project;
  /**
   * chat_sessions.id of the conversation that produced this, if any. Not a foreign key — see the field comment.
   */
  session?: number | null;
  /**
   * runs.id of the run that produced this, if any. Not a foreign key — see the `session` field comment.
   */
  run?: number | null;
  /**
   * Which agent authored it, so the Artifacts list can be filtered by author. Empty for an artifact a human made.
   */
  createdByAgent?: (number | null) | Agent;
  /**
   * The task this came out of, if it came out of one. Optional since R8.2.
   */
  task?: (number | null) | Task;
  /**
   * Legacy P2.1 external reference. Page and HTML artifacts leave this empty; their address derives from the record.
   */
  url?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plugins".
 */
export interface Plugin {
  id: number;
  name: string;
  workspace: number | Workspace;
  /**
   * Shown wherever this plugin is offered. What it lets an agent do, in a sentence.
   */
  description?: string | null;
  transport: 'http' | 'sse' | 'stdio';
  /**
   * Absolute URL of the MCP endpoint.
   */
  url?: string | null;
  /**
   * Executable to spawn.
   */
  command?: string | null;
  args?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  headers?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  env?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  enabled?: boolean | null;
  scope: 'agents' | 'workspace';
  agents?: (number | Agent)[] | null;
  configOptions?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "runtimes".
 */
export interface Runtime {
  id: number;
  name: string;
  workspace: number | Workspace;
  runtimeProfile: number | RuntimeProfile;
  host: string;
  connectionInfo?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status: 'up' | 'down' | 'unknown';
  lastCheckedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "approvals".
 */
export interface Approval {
  id: number;
  /**
   * The broker run id that triggered this approval request (raw pg runs table, not a Payload collection).
   */
  runId?: number | null;
  /**
   * ACP session/request_permission id — used to correlate with the ACP client.
   */
  externalId: string;
  /**
   * The user who can approve or deny this request.
   */
  requestedUser: number | User;
  title: string;
  detail?: string | null;
  options:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status: 'pending' | 'approved' | 'denied' | 'timeout';
  /**
   * The optionId the user selected when answering.
   */
  selectedOptionId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "saved-views".
 */
export interface SavedView {
  id: number;
  name: string;
  scope: 'workspace' | 'project' | 'mine';
  workspace: number | Workspace;
  /**
   * Only set (and only meaningful) when scope is 'project' — cleared by this collection's own beforeChange hook otherwise.
   */
  project?: (number | null) | Project;
  /**
   * Only set (and only meaningful) when scope is 'mine' — cleared by this collection's own beforeChange hook otherwise. The CRUD actions (saved-views-actions.ts) always scope 'mine' reads/writes to the requesting user's own id, never trusting a client-supplied owner.
   */
  owner?: (number | null) | User;
  /**
   * Who created this view — same explicit-caller pattern as Tasks.createdBy (no req.user inside Payload hooks in this app; see collections/Tasks.ts).
   */
  createdBy: number | User;
  /**
   * Serialized TaskViewConfig (lib/task-views/types.ts) — filters/sort/groupBy/columns/density. Opaque to Payload, same pattern as Agents.customEnv/customArgs/mcpConfig.
   */
  config:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "push-subscriptions".
 */
export interface PushSubscription {
  id: number;
  /**
   * Who this browser subscription belongs to. A user can have many (multiple browsers/devices).
   */
  user: number | User;
  /**
   * The PushSubscription's endpoint URL — globally unique per subscription; the upsert key on re-subscribe.
   */
  endpoint: string;
  /**
   * PushSubscription.toJSON().keys.p256dh — the subscription's public key.
   */
  p256dh: string;
  /**
   * PushSubscription.toJSON().keys.auth — the subscription's auth secret.
   */
  auth: string;
  /**
   * Best-effort context for a human pruning stale subscriptions; never parsed programmatically.
   */
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-preferences".
 */
export interface NotificationPreference {
  id: number;
  user: number | User;
  /**
   * Push a browser notification when a new approval needs this user.
   */
  pushApprovals?: boolean | null;
  /**
   * Push a browser notification when a run this user is accountable/originating for completes or fails.
   */
  pushCompletions?: boolean | null;
  /**
   * Push a browser notification when this user is @mentioned.
   */
  pushMentions?: boolean | null;
  /**
   * Opt-in daily email digest (pending approvals + completions since the last digest). The digest query itself is real (lib/notifications/digest.ts); actual email sending/scheduling is an explicitly documented gap, not faked — see that file.
   */
  emailDigestEnabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-resources".
 */
export interface ProjectResource {
  id: number;
  project: number | Project;
  kind: 'git_repo' | 'local_dir';
  /**
   * Absolute path on the runtime's filesystem — not the browser's. Empty for a git_repo not yet materialized (app-managed clones live under the runtime's workspace root, see AGENTS.md's Phase C notes).
   */
  path?: string | null;
  /**
   * git_repo only.
   */
  repoUrl?: string | null;
  /**
   * git_repo only.
   */
  defaultBranch?: string | null;
  /**
   * Exactly one primary per project — enforced by a DB constraint, not just this field.
   */
  role: 'primary' | 'reference' | 'output' | 'scratch';
  writable?: boolean | null;
  /**
   * Display order among a project's resources.
   */
  position?: number | null;
  lastVerifiedAt?: string | null;
  /**
   * Set by the runtime's last verification pass, not asserted by the browser.
   */
  exists?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workspace-members".
 */
export interface WorkspaceMember {
  id: number;
  workspace: number | Workspace;
  user: number | User;
  role: 'owner' | 'admin' | 'member' | 'viewer';
  /**
   * Null for the owner row created with the workspace itself.
   */
  invitedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invitations".
 */
export interface Invitation {
  id: number;
  workspace: number | Workspace;
  email: string;
  role: 'admin' | 'member' | 'viewer';
  /**
   * Random, single-use. The link is the credential, so it is never displayed after creation.
   */
  token: string;
  status: 'pending' | 'accepted' | 'revoked';
  invitedBy: number | User;
  acceptedBy?: (number | null) | User;
  expiresAt: string;
  /**
   * Optional broker `teams.id` to join on accept. A number rather than a relationship because channels live in the raw-pg broker, not in Payload.
   */
  channelId?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "access-grants".
 */
export interface AccessGrant {
  id: number;
  workspace: number | Workspace;
  objectType: 'project' | 'agent' | 'channel';
  /**
   * Text, because a channel id is a broker bigint and a project id is a Payload integer.
   */
  objectId: string;
  /**
   * Exactly one of subjectUser / subjectAgent is set.
   */
  subjectUser?: (number | null) | User;
  subjectAgent?: (number | null) | Agent;
  role: 'viewer' | 'editor' | 'admin';
  grantedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "connectors".
 */
export interface Connector {
  id: number;
  workspace: number | Workspace;
  /**
   * One value today. It is a column rather than an assumption so that a second broker — or a direct OAuth integration we own — does not need a migration.
   */
  provider: 'composio';
  /**
   * Composio's own identifier, e.g. `gmail`, `slack`, `github`. Never a display name.
   */
  toolkitSlug: string;
  /**
   * What a person calls it. Defaults to the toolkit name.
   */
  name: string;
  scopeType: 'workspace' | 'project' | 'agent';
  /**
   * The project or agent id. Null when `scopeType` is `workspace`.
   */
  scopeId?: string | null;
  /**
   * Composio's auth-config id for this toolkit. Created once per toolkit per workspace and reused by every person who connects — it is configuration, not a credential.
   */
  authConfigId?: string | null;
  /**
   * Tool slugs an agent may call, or empty for all of them. A connector that grants a whole toolkit when the job needs one action is the difference between "read my calendar" and "send mail as me".
   */
  allowedTools?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  enabled?: boolean | null;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "connections".
 */
export interface Connection {
  id: number;
  workspace: number | Workspace;
  user: number | User;
  toolkitSlug: string;
  /**
   * Composio's id for this authorised account. Null while the auth flow is still open.
   */
  composioConnectedAccountId?: string | null;
  status: 'pending' | 'active' | 'failed' | 'revoked';
  /**
   * Whatever the provider said when it went wrong. The most useful string on the screen when it does.
   */
  statusDetail?: string | null;
  /**
   * The URL the person has to visit to authorise. Held while the flow is open so a run parked on a connection can show the same link again rather than starting a second flow.
   */
  redirectUrl?: string | null;
  /**
   * The broker run id that asked for this connection, when an agent asked mid-turn. A number because runs are raw-pg, not Payload.
   */
  requestedByRun?: number | null;
  lastCheckedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'workspaces';
        value: number | Workspace;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'databases';
        value: number | Database;
      } | null)
    | ({
        relationTo: 'database-rows';
        value: number | DatabaseRow;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'task-statuses';
        value: number | TaskStatus;
      } | null)
    | ({
        relationTo: 'tasks';
        value: number | Task;
      } | null)
    | ({
        relationTo: 'task-links';
        value: number | TaskLink;
      } | null)
    | ({
        relationTo: 'followers';
        value: number | Follower;
      } | null)
    | ({
        relationTo: 'comments';
        value: number | Comment;
      } | null)
    | ({
        relationTo: 'activity';
        value: number | Activity;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'artifacts';
        value: number | Artifact;
      } | null)
    | ({
        relationTo: 'plugins';
        value: number | Plugin;
      } | null)
    | ({
        relationTo: 'runtime-profiles';
        value: number | RuntimeProfile;
      } | null)
    | ({
        relationTo: 'runtimes';
        value: number | Runtime;
      } | null)
    | ({
        relationTo: 'agents';
        value: number | Agent;
      } | null)
    | ({
        relationTo: 'approvals';
        value: number | Approval;
      } | null)
    | ({
        relationTo: 'saved-views';
        value: number | SavedView;
      } | null)
    | ({
        relationTo: 'push-subscriptions';
        value: number | PushSubscription;
      } | null)
    | ({
        relationTo: 'notification-preferences';
        value: number | NotificationPreference;
      } | null)
    | ({
        relationTo: 'project-resources';
        value: number | ProjectResource;
      } | null)
    | ({
        relationTo: 'workspace-members';
        value: number | WorkspaceMember;
      } | null)
    | ({
        relationTo: 'invitations';
        value: number | Invitation;
      } | null)
    | ({
        relationTo: 'access-grants';
        value: number | AccessGrant;
      } | null)
    | ({
        relationTo: 'connectors';
        value: number | Connector;
      } | null)
    | ({
        relationTo: 'connections';
        value: number | Connection;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  avatar?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workspaces_select".
 */
export interface WorkspacesSelect<T extends boolean = true> {
  composioApiKey?: T;
  name?: T;
  slug?: T;
  icon?: T;
  owner?: T;
  members?: T;
  taskPrefix?: T;
  taskCounter?: T;
  spendCapCents?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  icon?: T;
  coverImage?: T;
  workspace?: T;
  linkedSourceType?: T;
  linkedSourceId?: T;
  linkedRecordId?: T;
  parentPage?: T;
  project?: T;
  position?: T;
  docState?: T;
  plainTextContent?: T;
  isFavorite?: T;
  isArchived?: T;
  isFullWidth?: T;
  isLocked?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "databases_select".
 */
export interface DatabasesSelect<T extends boolean = true> {
  name?: T;
  workspace?: T;
  fields?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "database-rows_select".
 */
export interface DatabaseRowsSelect<T extends boolean = true> {
  database?: T;
  cells?: T;
  position?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  name?: T;
  workspace?: T;
  icon?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "task-statuses_select".
 */
export interface TaskStatusesSelect<T extends boolean = true> {
  workspace?: T;
  name?: T;
  category?: T;
  color?: T;
  position?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tasks_select".
 */
export interface TasksSelect<T extends boolean = true> {
  title?: T;
  workspace?: T;
  project?: T;
  status?: T;
  assignee?: T;
  agent?: T;
  page?: T;
  createdBy?: T;
  position?: T;
  revision?: T;
  lastActivityAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "task-links_select".
 */
export interface TaskLinksSelect<T extends boolean = true> {
  fromTask?: T;
  toTask?: T;
  linkType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "followers_select".
 */
export interface FollowersSelect<T extends boolean = true> {
  user?: T;
  entityType?: T;
  entityId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments_select".
 */
export interface CommentsSelect<T extends boolean = true> {
  task?: T;
  author?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity_select".
 */
export interface ActivitySelect<T extends boolean = true> {
  entityType?: T;
  entityId?: T;
  actor?: T;
  action?: T;
  payload?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  user?: T;
  activity?: T;
  message?: T;
  isRead?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artifacts_select".
 */
export interface ArtifactsSelect<T extends boolean = true> {
  workspace?: T;
  name?: T;
  kind?: T;
  page?: T;
  pageSubtreeBlockId?: T;
  htmlContent?: T;
  project?: T;
  session?: T;
  run?: T;
  createdByAgent?: T;
  task?: T;
  url?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plugins_select".
 */
export interface PluginsSelect<T extends boolean = true> {
  name?: T;
  workspace?: T;
  description?: T;
  transport?: T;
  url?: T;
  command?: T;
  args?: T;
  headers?: T;
  env?: T;
  enabled?: T;
  scope?: T;
  agents?: T;
  configOptions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "runtime-profiles_select".
 */
export interface RuntimeProfilesSelect<T extends boolean = true> {
  name?: T;
  workspace?: T;
  protocolFamily?: T;
  commandName?: T;
  fixedArgs?: T;
  enabled?: T;
  homeStrategy?: T;
  handshake?: T;
  defaultSessionConfig?: T;
  lastProbeCode?: T;
  lastProbeDetail?: T;
  lastProbedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "runtimes_select".
 */
export interface RuntimesSelect<T extends boolean = true> {
  name?: T;
  workspace?: T;
  runtimeProfile?: T;
  host?: T;
  connectionInfo?: T;
  status?: T;
  lastCheckedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agents_select".
 */
export interface AgentsSelect<T extends boolean = true> {
  name?: T;
  workspace?: T;
  runtimeProfile?: T;
  model?: T;
  hermesProfile?: T;
  runtimeConfig?: T;
  thinkingLevel?: T;
  instructions?: T;
  customEnv?: T;
  customArgs?: T;
  mcpConfig?: T;
  skills?: T;
  maxConcurrentRuns?: T;
  permissionMode?: T;
  enabled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "approvals_select".
 */
export interface ApprovalsSelect<T extends boolean = true> {
  runId?: T;
  externalId?: T;
  requestedUser?: T;
  title?: T;
  detail?: T;
  options?: T;
  status?: T;
  selectedOptionId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "saved-views_select".
 */
export interface SavedViewsSelect<T extends boolean = true> {
  name?: T;
  scope?: T;
  workspace?: T;
  project?: T;
  owner?: T;
  createdBy?: T;
  config?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "push-subscriptions_select".
 */
export interface PushSubscriptionsSelect<T extends boolean = true> {
  user?: T;
  endpoint?: T;
  p256dh?: T;
  auth?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-preferences_select".
 */
export interface NotificationPreferencesSelect<T extends boolean = true> {
  user?: T;
  pushApprovals?: T;
  pushCompletions?: T;
  pushMentions?: T;
  emailDigestEnabled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-resources_select".
 */
export interface ProjectResourcesSelect<T extends boolean = true> {
  project?: T;
  kind?: T;
  path?: T;
  repoUrl?: T;
  defaultBranch?: T;
  role?: T;
  writable?: T;
  position?: T;
  lastVerifiedAt?: T;
  exists?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workspace-members_select".
 */
export interface WorkspaceMembersSelect<T extends boolean = true> {
  workspace?: T;
  user?: T;
  role?: T;
  invitedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invitations_select".
 */
export interface InvitationsSelect<T extends boolean = true> {
  workspace?: T;
  email?: T;
  role?: T;
  token?: T;
  status?: T;
  invitedBy?: T;
  acceptedBy?: T;
  expiresAt?: T;
  channelId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "access-grants_select".
 */
export interface AccessGrantsSelect<T extends boolean = true> {
  workspace?: T;
  objectType?: T;
  objectId?: T;
  subjectUser?: T;
  subjectAgent?: T;
  role?: T;
  grantedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "connectors_select".
 */
export interface ConnectorsSelect<T extends boolean = true> {
  workspace?: T;
  provider?: T;
  toolkitSlug?: T;
  name?: T;
  scopeType?: T;
  scopeId?: T;
  authConfigId?: T;
  allowedTools?: T;
  enabled?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "connections_select".
 */
export interface ConnectionsSelect<T extends boolean = true> {
  workspace?: T;
  user?: T;
  toolkitSlug?: T;
  composioConnectedAccountId?: T;
  status?: T;
  statusDetail?: T;
  redirectUrl?: T;
  requestedByRun?: T;
  lastCheckedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hermes-config".
 */
export interface HermesConfig {
  id: number;
  /**
   * e.g. https://your-hermes-host/v1
   */
  baseUrl?: string | null;
  /**
   * Bearer token for Hermes requests, if your Hermes install requires one.
   */
  apiKey?: string | null;
  verified?: boolean | null;
  lastVerifiedAt?: string | null;
  /**
   * Set by the last failed Test Connection attempt.
   */
  lastError?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hermes-config_select".
 */
export interface HermesConfigSelect<T extends boolean = true> {
  baseUrl?: T;
  apiKey?: T;
  verified?: T;
  lastVerifiedAt?: T;
  lastError?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}